create table visitors (
  PRIMARY KEY (id)
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ip varchar2(50) not null,
  user_agent VARCHAR2(255) not null,
  visit_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

insert into visitors values('°¡Çö', );


select * from visitors;

 create table account_test(
    a_name varchar2(20 char) not null,
    a_id varchar2(20 char) primary key,
    a_pw varchar2(20 char) not null,
    a_gender char(1 char) not null,
    a_addr varchar2(100 char) not null,
    a_interest varchar2(200 char) not null,
    a_introduce varchar2(200 char) not null,
    a_img varchar2(300 char) not null
);